### ISSUE TITLE
doctl uses the wrong executable name in kubeconfig

### ISSUE THREAD

**Issue by davidsbond** [digitalocean/doctl#1042]
**Describe the Issue:**

I ran the `kubeconfig` save command within the terminal in my Goland IDE:

```
doctl kubernetes cluster kubeconfig save <id>
```

When my kubeconfig was modified, it used `goland` as the executable instead of `doctl`. This caused any usage of that cluster to open goland with a bunch of empty files:

```yaml
- name: <name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - <id>
      command: goland
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

I haven't looked at the source, but I imagine it's using the executable name from `os.Args`, which is likely being modified by the goland terminal. It must be passing all commands through `goland` first. 

I assume the reason for doing this is so that someone can rename the `doctl` executable, but perhaps that should just be hard-coded instead.

**Environment:**

 - doctl version: 1.65.0
 - OS: Ubuntu
 - Installation method: `go install`
