### ISSUE TITLE
preserve_path_prefix is missing

### ISSUE THREAD

**Issue by tobias-kuendig** [digitalocean/doctl#1064]
According to the app spec documentation, there is a `preserve_path_prefix` option under `services.routes`. This is missing in doctl and therefore leads to an error.

Example YAML:
```yaml
services:
- name: example
  routes:
    - path: /example
      preserve_path_prefix: true
```

Error:
> Error: parsing app spec: json: unknown field "preserve_path_prefix"

Doc:
https://docs.digitalocean.com/products/app-platform/references/app-specification-reference/#ref-services-routes-preserve_path_prefix

Struct:
https://github.com/digitalocean/doctl/blob/3d6466a9bce767addfed411ef56fba206e38126a/vendor/github.com/digitalocean/godo/apps.gen.go#L229

doctl version:

```
doctl version 1.67.0-release
Git commit hash: 535f1031
```
