### ISSUE TITLE
`doctl apps spec validate app.yml` returns error when `health_check.port` is used

### ISSUE THREAD

**Issue by fx-adr** [digitalocean/doctl#1217]
**Describe the Issue:**

Running `doctl apps spec validate app.yml` throws validation error when `port` is used within health_check block.

Returns error:
`Error: parsing app spec: json: unknown field "port"`

**Environment:**
 - doctl version: `doctl version 1.64.0-release`
 - OS & Install: Docker Image `alpine/doctl:latest`

**Additional Details:**

app.yml:
```yml
domains:
  - domain: my-domain.com
    type: PRIMARY
name: my-do-app-name
region: sfo
services:
  - http_port: 3000
    health_check:
      http_path: /misc/up
      failure_threshold: 5
      initial_delay_seconds: 2
      period_seconds: 10
      port: 3000
      success_threshold: 2
      timeout_seconds: 2
    image:
      registry_type: DOCR
      repository: my-repo
      tag: latest
    instance_count: 1
    instance_size_slug: professional-xs
    name: my-do-app-name
    routes:
      - path: /
``` 

Adding the values other than `http_path` within `health_check` causes this error.
