### ISSUE TITLE
Microservices deployment -> doctl - create with upsert and update fails to update app component

### ISSUE THREAD

**Issue by homihq** [digitalocean/doctl#1322]
**Describe the Issue:**

Trying to host an app on DO. This app comprises of two components. Trying to achieve this via Github actions.
The first app in an HTTP app - so when the update is attempted after a push to a branch it complains

`Run doctl apps create *** --spec /home/runner/work/digitalocean-deploy/digitalocean-deploy/merged.yml --upsert true
Error: POST https://api.digitalocean.com/v2/apps: [4](https://github.com/homihq/digitalocean-deploy/actions/runs/3644754936/jobs/6154299054#step:7:5)00 (request "466eeae8-7ac8-48e6-8236-dda52f837af6") error validating app spec field "services.route.paths": route path "/" already in use; seen in service "homihq-api-gateway" and service "homihq-api-gateway"`

The other app is an internal app only accessible from this HTTP service. This also fails 

`Run doctl apps create *** --spec /home/runner/work/product-service/product-service/merged.yml --upsert true
Error: POST https://api.digitalocean.com/v2/apps: 400 (request "64f4e194-b224-428c-b15d-3c2b82d25eb6") error validating app spec field "services.name": service "product-service" name conflicts with service "product-service"`

The expectation is code changes in the github repo the individual components should be independently changed and updated. 

**Environment:**
 - doctl version: doctl version 1.88.0-release Git commit hash: 106861d5
 - OS: Ubuntu 22.0 LTS
 - Installation method: 

**Additional Details:**
The repos are available here 

https://github.com/homihq/digitalocean-deploy
https://github.com/homihq/product-service

**Comment by andrewsomething** [comment]
Hi @homihq, 

I tried to reproduce this manually using the app spec from https://github.com/homihq/digitalocean-deploy At first, I was unsuccessful. I was able to run `doctl apps create --upsert --spec dospec.yml` repeatedly without issue. Then I noticed you are doing something slightly different in the workflow. You first fetch the spec and then merge it with the local version. I could reproduce the problem that way. 

```
$ doctl apps spec get $APPID > existing.yml
$ yaml-merge existing.yml dospec.yml > merged.yml
$ doctl apps create --upsert --spec merged.yml 
Error: POST https://api.digitalocean.com/v2/apps: 400 (request "369dc8e9-f640-4421-bb01-a10e06c83df7") errors validating app spec; first error in field "services.name": service "homihq-api-gateway" name conflicts with service "homihq-api-gateway"
```

Looking at the `merged.yml` file produced by `yaml-merge`, I can see the problem:

```
envs:
  - key: GITHUB_WEBHOOK_SECRET
    scope: RUN_AND_BUILD_TIME
    value: sdfsf
  - key: GITHUB_WEBHOOK_SECRET
    scope: RUN_AND_BUILD_TIME
    value: sdfsf
name: plankton-app
region: nyc
services:
  - http_port: 8080
    image:
      registry: homihq
      registry_type: DOCKER_HUB
      repository: micro-gateway
      tag: latest
    instance_count: 1
    instance_size_slug: professional-xs
    name: homihq-api-gateway
    routes:
      - path: /
  - name: homihq-api-gateway
    http_port: 8080
    image:
      registry: homihq
      registry_type: DOCKER_HUB
      repository: micro-gateway
      tag: latest
    instance_count: 1
    instance_size_slug: professional-xs
```

For some reason, `yaml-merge` seems to be duplicating things instead of merging them correctly.
