### ISSUE TITLE
serverless project init uses `websecure` string instead of `webSecure` when generating project template

### ISSUE THREAD

**Issue by rabbah** [digitalocean/doctl#1341]
**Describe the Issue:**
```bash
doctl sls init -l js foo
```

Generates `project.yml`:
```yml
parameters: {}
environment: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
```

The `project.yml` contains a `websecure: false` property. The [schema calls for `webSecure`](https://github.com/digitalocean/functions-deployer/blob/0a25dc78dcdadb75fb409defb681bcfc440e6fba/src/deploy-struct.ts#L55). Changing the `false` to `true` results in an error at deploy time:
```
Error: Invalid project configuration file (project.yml): Invalid key 'websecure' found in 'action' clause in project.yml 
```

The proper key should be generated

**Environment:**

 - doctl version: 1.92
 - OS: macos 
 - Installation method: github release 

**Additional Details:**
