### ISSUE TITLE
Serverless triggers are not being deployed

### ISSUE THREAD

**Issue by davidsbond** [digitalocean/doctl#1474]
**Describe the Issue:**

Hi! I'm trying to use doctl to deploy a serverless function with a cron trigger. When I run the `doctl serverless deploy` command my function is deployed but the trigger is not.  I do not see a section in my console output for the trigger.

**Environment:**

 - doctl version: `1.101.0-release`
 - OS: Ubuntu
 - Installation method: Snap

**Additional Details:**

Adding a `trace` flag provides no additional output.

**Comment by davidsbond** [comment]
Ah, it seems like scheduling doesn't work with go functions. Is this intended behaviour?

**Comment by andrewsomething** [comment]
@davidsbond  I've confirmed with the Serverless team that it is currently the expected behavior. Unfortunately, triggers are not deployed when using remote builds and Go functions are always remote builds. Triggers can be used with Go functions, but they must be created in the control panel for now.

Let's keep this issue open for tracking. Even though it is the current behavior, it is something we should support in the future.

**Comment by steevehook** [comment]
The Digital Ocean cripling signature. Waiting for a product that works as expected

**Comment by pippinmole** [comment]
Hi,

I'm getting the same behaviour, but with python cron jobs.

```yml
packages:
  - name: my_package
    functions:
      - name: my_name
        runtime: python:3.11
        limits:
          memory: 512 # MB
        triggers:
          - name: cron-trigger
            sourceType: scheduler
            sourceDetails:
              cron: "0/15 * * * *" # every 15 minutes
```

Running:

```bash
doctl serverless deploy . --remote-build
```

And it's not showing up in the dashboard:

![image](https://github.com/digitalocean/doctl/assets/40035529/4ffc5b7f-481e-4063-ba56-858f9216799b)

**Environment:**

    doctl version: 1.103.0-release
    OS: Windows

Really looking forward to this being fixed :)
