### ISSUE TITLE
functions: attributes generated by quick start is undocumented 

### ISSUE THREAD

**Issue by KylePeterDavies** [digitalocean/doctl#1534]
**Describe the Issue:**

If you generate a quick start for `Go` with `doctl` ...

```bash
doctl serverless init --language go test
```

`doctl` will generate a quick start and it's `project.yml` for the language. If you inspect the generated `project.yml`

```yaml
parameters: {}
environment: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: go:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
```

The `binary` and `annotations` attributes are undocumented at [Project Configuration YAML File](https://docs.digitalocean.com/products/functions/reference/project-configuration/)

**Environment:**
```
doctl version 1.105.0-release
release 1.106.0 is available, check it out! 
```
