### ISSUE TITLE
Functions node flag --env not working?

### ISSUE THREAD

**Issue by Benjythebee** [digitalocean/doctl#1537]
**Describe the Issue:**

I've been trying to deploy a relatively simple function written in js with the following structure:
```
packages
-- mypackage
-- -- myfunction
-- -- -- index.js
.env
project.yml
```

I have the deploy command `doctl serverless deploy --build-env ./.env --env ./.env -v --verbose-build`.
The problem is whatever I do the command does not add/update the environment variables. If I added the environment variables manually in the UI, the deploy command apparently overwrites the envs and I end up with `0 Environment variables`

I've been doing lots of googling and have no idea why the .env file is not picked up and why the envs are not being passed.

I have also tried `--build-env .env --env .env ...`

I had found this Q&A topic:
https://www.digitalocean.com/community/questions/how-to-access-environment-variables-defined-in-function-settings-tab
```
By default, the doctl serverless deploy command will look for an .env file in the same directory as the project.yml file.
```

So I also tried the command without the `--build-env` flag and `--env` flag.

I have no clue why it's not working and from my googling it looks like lots of people seem confused with these flags so it might just be a bug? Please mark this ticket as duplicate if someone else already made an issue about this.

**Environment:**
 - doctl version: v1.104.0-release (and v1.107.0)
 - OS: Windows 11
 - Installation method: Powershell

**Comment by andrewsomething** [comment]
Hi @Benjythebee,

Are your variables defined in your `project.yml` file? For example, if your `.env` file looks like

```
FOO=bar
```

Your  `project.yml` file might look like:

```
parameters: {}
environment: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          webSecure: false
          parameters: {}
          environment:
            FOO: "${FOO}"
          annotations: {}
          limits: {}
```

For more detail see: https://docs.digitalocean.com/products/functions/reference/project-configuration/
