### ISSUE TITLE
functions: runtime of go:1.20 ignored 

### ISSUE THREAD

**Issue by KylePeterDavies** [digitalocean/doctl#1637]
**Describe the Issue:**

Can't create Digital Ocean Go Function with `go:1.20` instead I get `go:1.17`. 

```yaml
packages:
  - name: webhooks
    functions:
      - name: notifier2
        runtime: go:1.20
        web: false
```

```
doctl serverless deploy packages/webhooks
```

```
Deploying '/Users/kyle.davies/Desktop/DigitalOcean-Function-Discord-Webhook/packages/webhooks'
  to namespace 'fn-141fc203-4469-40e6-9931-7291b69433b9'
  on host 'https://faas-ams3-2a2df116.doserverless.co'
Nothing deployed
```

I also can't understand why it states `Nothing Deployed` but creates the function anyway?

<img width="1057" alt="Screenshot 2025-01-11 at 16 16 34" src="https://github.com/user-attachments/assets/38a71b6c-0436-4321-ab07-363c631619a3" />

**Environment:**

 - doctl version: doctl version 1.120.1-release
 - OS: Apple MacOS 15.0 (24A335)
 - Installation method: homebrew 

**Additional Details:**
