### ISSUE TITLE
[Question] How to re-use token between calls

### ISSUE THREAD

**Issue by Kikobeats** [digitalocean/doctl#640]
Hello,

I want to deploy into a kubernetes cluster from a CD/CI.

For doing that, I'm installing `doctl` and setup an API token with `Read/Write` permissions as `DIGITALOCEAN_ACCESS_TOKEN`.

![Screenshot 2019-10-10 at 17 41 33](https://user-images.githubusercontent.com/2096101/66584337-3c846c80-eb85-11e9-94ba-028e6700dc78.png)

My code looks like

```yml
# installing `doctl`
- DIGITALOCEAN_ACCESS_TOKEN=my-read-write-token
- DOCTL_VERSION=$(curl -fsL https://api.github.com/repos/digitalocean/doctl/releases/latest | jq -r ".tag_name" | sed 's/v//')
- curl -fsL https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz | tar xz
- mv doctl /usr/local/bin
# initialize `doctl`
- doctl kubernetes cluster kubeconfig save my-cluster
```

After that, I execute the command for fetching my cluster configuration, and all is working fine, however, I noted that every time I do that, a new read-only token is generated:

![Screenshot 2019-10-10 at 17 41 36](https://user-images.githubusercontent.com/2096101/66584351-4312e400-eb85-11e9-8d67-212a252d239d.png)

My question is, essentially, why a read-only token is generated?

How I can avoid that? Why not the process is using the read/write token provided as env variable?

**Comment by andrewsomething** [comment]
You are seeing this due to a recent change in how DOKS Kubernetes clusters handle authentication. Rather than using certificates, they now use API tokens. This gives team administrators much finer control over how their clusters can be accessed. Rather than a shared certificate that can not be revoked, a token tied to a specific kubeconfig file can be revoked without breaking other users.

You can read more about those changes here:

https://blog.digitalocean.com/new-on-digitalocean-kubernetes/
https://www.digitalocean.com/docs/kubernetes/how-to/connect-to-cluster/#automatically-managed-tokens-recommended

If you are able to reuse `~/.config/doctl/cache/exec-credential` across CI runs, only one token will be generated and reused. To prevent the tokens from being generated all together, you can craft a kubeconfig file using a normal DO API token.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CA data>
    server: https://<cluster-id>.k8s.ondigitalocean.com
  name: do-lon1-cluster-name
contexts:
- context:
    cluster: do-lon1-cluster-name
    user: do-lon1-cluster-name-admin
  name: do-lon1-cluster-name
current-context: do-lon1-cluster-name
kind: Config
preferences: {}
users:
- name: do-lon1-cluster-name-admin
  user:
    token: <a DO api token>
```
