### ISSUE TITLE
DO container registry k8s deployment pulling error

### ISSUE THREAD

**Issue by anthonysanchezmk** [digitalocean/doctl#847]
**Describe the Issue:**
When i deploy with an image hosted on the digital ocean container registry in any namespace besides the default there will be an error (no authorization). Once I make a deployment in the default namespace, the other namespaces are able to properly pull the container.

**Environment:**

 - doctl version: 
 - OS: 
 - Installation method: 

**Additional Details:**

**Comment by andrewsomething** [comment]
Hi @anthonysanchezmk ,

How are you adding the credentials to the cluster? The Kubernetes secrets manifest that is created when you run:

`doctl registry kubernetes-manifest | kubectl apply -f -`

specifies the default namespace. Something like:

```
apiVersion: v1
data:
  .dockerconfigjson: REDACEDSECRETS
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-name
  namespace: default
type: kubernetes.io/dockerconfigjson
```
