### ISSUE TITLE
Doctl Returns 500 Error When deploying app.yaml to DO App Platform (image source)

### ISSUE THREAD

**Issue by farwydi** [digitalocean/doctl#923]
**Describe the Issue:**

I've created a YAML spec for my DO App Platform.

Which looks like this:

```yaml
name: redmine-do
region: fra
services:
- name: redmine-dockerfile
  image:
    registry: index.docker.io/v1
    repository: redmine
    tag: 4.1.1
  envs:
  - key: REDMINE_DB_POSTGRES
    scope: RUN_TIME
    value: ${redmine-databases.DATABASE_URL}
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
databases:
- engine: PG
  name: redmine-databases
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
```

But when I try to execute:
```bash
doctl apps create --spec app.yaml
```

It returns a 500 Error and nothing else. I've tried executing the command locally. I'm able to access other resources on my DO account but I can't successfully create the spec.

Do you know what could be going wrong?

**Environment:**

* doctl version: 1.51.0
* OS: Windows (Git Bash)
* Installation method: Installed from release page

**Additional Details:**

This is the specific error I get back from doctl:
Error: POST https://api.digitalocean.com/v2/apps: 500 Server Error

This is the output of the command with the trace flag turned out.
P.S. I formatted to be more readable.
```
doctl: 2020/12/01 13:52:23 -> "POST /v2/apps HTTP/1.1
Host: api.digitalocean.com
User-Agent: doctl/1.51.0-release (windows amd64) godo/1.51.0
Content-Length: 396
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{
   "spec":{
      "name":"redmine-do",
      "services":[
         {
            "name":"redmine-dockerfile",
            "envs":[
               {
                  "key":"REDMINE_DB_POSTGRES",
                  "value":"${redmine-databases.DATABASE_URL}",
                  "scope":"RUN_TIME"
               }
            ],
            "instance_size_slug":"basic-xs",
            "instance_count":1,
            "http_port":3000,
            "routes":[
               {
                  "path":"/"
               }
            ]
         }
      ],
      "databases":[
         {
            "name":"redmine-databases",
            "engine":"PG",
            "version":"12",
            "size":"db-s-dev-database",
            "num_nodes":1
         }
      ],
      "region":"fra"
   }
}
doctl: 2020/12/01 13:52:23 <- "HTTP/2.0 500 Internal Server Error
Content-Length: 59
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5fac42240de05aaa-DME
Cf-Request-Id: 06bf87aa8400005aaaf1a9a000000001
Content-Type: application/json
Date: Tue, 01 Dec 2020 10:52:23 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d03379124a2f65ccc4db05086f4c278b91606819943; expires=Thu, 31-Dec-20 10:52:23 GMT; path=/; domain=.digitalocean.com; HttpOnly; SameSite=Lax
X-Gateway: Edge-Gateway
X-Request-Id: dbc4f7e5-114a-4e3e-a9ed-ad7b67775398
X-Response-From: service

{
   "id":"Internal Server Error",
   "message":"Server Error"
}
Error: POST https://api.digitalocean.com/v2/apps: 500 Server Error
```
